=== luca99999/Socket/Socket-Udp/Generic-Udp/xml/viaggi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="viaggi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="paese" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="capitale" type="xs:string"/>
							<xs:element name="giorni" type="xs:integer"/>
							<xs:element name="costo" type="xs:decimal"/>
							<xs:element name="stagione" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="nome" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== luca99999/Socket/Socket-Udp/Generic-Udp/xml/viaggischema.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="viaggi.css" ?>
<viaggi
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="viaggi.xsd">
<!-- questo Ã¨ un commento -->
<paese nome="Italia">
<capitale>Roma</capitale>
<giorni>10</giorni>
<costo>1000.00</costo>
<stagione>Primavera</stagione>
</paese>
<paese nome="Francia">
<capitale>Parigi</capitale>
<giorni>15</giorni>
<costo>2000.50</costo>
<stagione>Estate</stagione>
</paese>
</viaggi>
